org.gradle.jvmargs=-Xmx8G
org.gradle.configuration-cache=true

# fabric
loader_version=0.18.4
loom_version=1.15-SNAPSHOT

# preprocessor
discombobulator_version=1.4

# mod
mod_name=MobandBlockHelper
mod_version=1.0.0
maven_group=com.minecrafttas
release=false

# Mod properties
mod_description=Overrides mob and block drops for use with non-playback TASes until KilltheRNG is stable.
mod_url=https://minecrafttas.com
mod_sources=https://github.com/Unease/
mod_email=uneasepurse37@gmail.com